[package]
name = "rust"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket_okapi = "0.7.0-alpha-1"
okapi = "0.6.0-alpha-1"
diesel = { version = "1.4.4", features = ["mysql", "r2d2"] }
dotenv = "0.15.0"
serde = "1.0.130"
